version: '3.8'

services:
  # Ollama service with GPU support
  ollama:
    image: ollama/ollama:latest
    container_name: staging-ollama-gpu
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ai-network
    restart: unless-stopped

  # API Server (with Ollama integration)
  api:
    build: .
    container_name: staging-api-test
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TOKENIZERS_PARALLELISM=false
      - HF_HOME=/app/cache/huggingface
      # External dependencies configuration
      - SKIP_OPENSEARCH=true
      - SKIP_REDIS=true
      - SKIP_OLLAMA=false
      - OLLAMA_BASE_URL=http://ollama:11434
      - DOCKER_ENV=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./models:/app/models
      - model_cache:/root/.cache/huggingface
    depends_on:
      - ollama
    networks:
      - ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

volumes:
  ollama_data:
    driver: local
  model_cache:
    driver: local

networks:
  ai-network:
    driver: bridge
