# Docker Compose for AI Processing Suite - Staging Test
# Runs only the API service without OpenSearch/Redis

version: '3.8'

services:
  ai-processing-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SKIP_OPENSEARCH=true
      - SKIP_REDIS=true
      - DOCKER_ENV=true
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TOKENIZERS_PARALLELISM=false
    volumes:
      # Optional: Mount for persistent model cache
      - model_cache:/root/.cache/huggingface
      # Optional: Mount logs for debugging
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  model_cache:
    driver: local
