name: test and Deploy to Azure VM edsico (Manual Service Startup)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Azure VM
      env:
        AZURE_VM_HOST: ${{ secrets.AZURE_VM_HOST }}
        AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
        AZURE_VM_SSH_KEY: ${{ secrets.AZURE_VM_SSH_KEY }}
      run: |
        # Add SSH key
        echo "${AZURE_VM_SSH_KEY}" > azure_vm_key
        chmod 600 azure_vm_key

        # SSH into the VM and deploy
        ssh -i azure_vm_key -o StrictHostKeyChecking=no $AZURE_VM_USERNAME@$AZURE_VM_HOST << 'EOF'
          set -e
          # Clone repo if missing
          if [ ! -d ~/llm-retrieval-system ]; then
            git clone  https://github.com/kmranikmr/ediscovery-review.git ~/llm-retrieval-system
          fi
          cd ~/llm-retrieval-system

          # Ensure it's a git repo and on the right branch
          git fetch origin master
          git checkout master
          git pull origin master

          # Ensure Python and pip are installed
          if ! command -v python3 &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y python3 python3-pip
          fi

          # Create venv if missing
          if [ ! -d venv ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate

          # Install requirements
          pip install --upgrade pip
          pip install -r requirements.txt

          # Ensure logs directory exists
          mkdir -p logs

          # Stop any running FastAPI service
          if [ -f fastapi.pid ]; then
            kill $(cat fastapi.pid) || true
            rm fastapi.pid
          fi

          # Stop any running Streamlit service
          if [ -f streamlit.pid ]; then
            kill $(cat streamlit.pid) || true
            rm streamlit.pid
          fi

          # Start FastAPI service
          nohup python main.py > logs/main.log 2>&1 &
          echo $! > fastapi.pid

          # Start Streamlit service
          nohup streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0 > logs/streamlit.log 2>&1 &
          echo $! > streamlit.pid
        EOF
